import { Country } from '../types/cricket';

export const FALLBACK_COUNTRIES_DATA: Country[] = [
  { id: 'IND', alpha2: 'IN', name: 'India', officialName: 'Republic of India', flagUrl: 'https://flagcdn.com/w160/in.png', emoji: '🇮🇳', isoCode: 'IND', fifaCode: 'IND', region: 'Asia', population: 1400000000, isSovereign: true },
  { id: 'AUS', alpha2: 'AU', name: 'Australia', officialName: 'Commonwealth of Australia', flagUrl: 'https://flagcdn.com/w160/au.png', emoji: '🇦🇺', isoCode: 'AUS', fifaCode: 'AUS', region: 'Oceania', population: 25687041, isSovereign: true },
  { id: 'ENG', alpha2: 'GB', name: 'England', officialName: 'England & Wales Cricket', flagUrl: 'https://flagcdn.com/w160/gb-eng.png', emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', isoCode: 'ENG', fifaCode: 'ENG', region: 'Europe', population: 56000000, isSovereign: true },
  { id: 'PAK', alpha2: 'PK', name: 'Pakistan', officialName: 'Islamic Republic of Pakistan', flagUrl: 'https://flagcdn.com/w160/pk.png', emoji: '🇵🇰', isoCode: 'PAK', fifaCode: 'PAK', region: 'Asia', population: 240000000, isSovereign: true },
  { id: 'RSA', alpha2: 'ZA', name: 'South Africa', officialName: 'Republic of South Africa', flagUrl: 'https://flagcdn.com/w160/za.png', emoji: '🇿🇦', isoCode: 'RSA', fifaCode: 'RSA', region: 'Africa', population: 60000000, isSovereign: true },
  { id: 'NZL', alpha2: 'NZ', name: 'New Zealand', officialName: 'New Zealand', flagUrl: 'https://flagcdn.com/w160/nz.png', emoji: '🇳🇿', isoCode: 'NZL', fifaCode: 'NZL', region: 'Oceania', population: 5000000, isSovereign: true },
  { id: 'SRI', alpha2: 'LK', name: 'Sri Lanka', officialName: 'Democratic Socialist Republic of Sri Lanka', flagUrl: 'https://flagcdn.com/w160/lk.png', emoji: '🇱🇰', isoCode: 'SRI', fifaCode: 'SRI', region: 'Asia', population: 22000000, isSovereign: true },
  { id: 'BAN', alpha2: 'BD', name: 'Bangladesh', officialName: 'People\'s Republic of Bangladesh', flagUrl: 'https://flagcdn.com/w160/bd.png', emoji: '🇧🇩', isoCode: 'BAN', fifaCode: 'BAN', region: 'Asia', population: 170000000, isSovereign: true },
  { id: 'AFG', alpha2: 'AF', name: 'Afghanistan', officialName: 'Islamic Republic of Afghanistan', flagUrl: 'https://flagcdn.com/w160/af.png', emoji: '🇦🇫', isoCode: 'AFG', fifaCode: 'AFG', region: 'Asia', population: 40000000, isSovereign: true },
  { id: 'WIN', alpha2: 'JM', name: 'West Indies', officialName: 'Cricket West Indies', flagUrl: 'https://flagcdn.com/w160/jm.png', emoji: '🌴', isoCode: 'WIN', fifaCode: 'WIN', region: 'Americas', population: 4000000, isSovereign: true },
  { id: 'ZIM', alpha2: 'ZW', name: 'Zimbabwe', officialName: 'Republic of Zimbabwe', flagUrl: 'https://flagcdn.com/w160/zw.png', emoji: '🇿🇼', isoCode: 'ZIM', fifaCode: 'ZIM', region: 'Africa', population: 15000000, isSovereign: true },
  { id: 'IRE', alpha2: 'IE', name: 'Ireland', officialName: 'Republic of Ireland', flagUrl: 'https://flagcdn.com/w160/ie.png', emoji: '🇮🇪', isoCode: 'IRE', fifaCode: 'IRE', region: 'Europe', population: 5000000, isSovereign: true },
  { id: 'NED', alpha2: 'NL', name: 'Netherlands', officialName: 'Kingdom of the Netherlands', flagUrl: 'https://flagcdn.com/w160/nl.png', emoji: '🇳🇱', isoCode: 'NED', fifaCode: 'NED', region: 'Europe', population: 17000000, isSovereign: true },
  { id: 'SCO', alpha2: 'GB', name: 'Scotland', officialName: 'Cricket Scotland', flagUrl: 'https://flagcdn.com/w160/gb-sct.png', emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', isoCode: 'SCO', fifaCode: 'SCO', region: 'Europe', population: 5400000, isSovereign: true },
  { id: 'NAM', alpha2: 'NA', name: 'Namibia', officialName: 'Republic of Namibia', flagUrl: 'https://flagcdn.com/w160/na.png', emoji: '🇳🇦', isoCode: 'NAM', fifaCode: 'NAM', region: 'Africa', population: 2500000, isSovereign: true },
  { id: 'NEP', alpha2: 'NP', name: 'Nepal', officialName: 'Federal Democratic Republic of Nepal', flagUrl: 'https://flagcdn.com/w160/np.png', emoji: '🇳🇵', isoCode: 'NEP', fifaCode: 'NEP', region: 'Asia', population: 30000000, isSovereign: true },
  { id: 'USA', alpha2: 'US', name: 'United States', officialName: 'United States of America', flagUrl: 'https://flagcdn.com/w160/us.png', emoji: '🇺🇸', isoCode: 'USA', fifaCode: 'USA', region: 'Americas', population: 330000000, isSovereign: true },
  { id: 'CAN', alpha2: 'CA', name: 'Canada', officialName: 'Canada', flagUrl: 'https://flagcdn.com/w160/ca.png', emoji: '🇨🇦', isoCode: 'CAN', fifaCode: 'CAN', region: 'Americas', population: 38000000, isSovereign: true },
  { id: 'OMA', alpha2: 'OM', name: 'Oman', officialName: 'Sultanate of Oman', flagUrl: 'https://flagcdn.com/w160/om.png', emoji: '🇴🇲', isoCode: 'OMA', fifaCode: 'OMA', region: 'Asia', population: 5000000, isSovereign: true },
  { id: 'UAE', alpha2: 'AE', name: 'United Arab Emirates', officialName: 'United Arab Emirates', flagUrl: 'https://flagcdn.com/w160/ae.png', emoji: '🇦🇪', isoCode: 'UAE', fifaCode: 'UAE', region: 'Asia', population: 9000000, isSovereign: true },
  { id: 'PNG', alpha2: 'PG', name: 'Papua New Guinea', officialName: 'Independent State of Papua New Guinea', flagUrl: 'https://flagcdn.com/w160/pg.png', emoji: '🇵🇬', isoCode: 'PNG', fifaCode: 'PNG', region: 'Oceania', population: 9000000, isSovereign: true },
  { id: 'UGA', alpha2: 'UG', name: 'Uganda', officialName: 'Republic of Uganda', flagUrl: 'https://flagcdn.com/w160/ug.png', emoji: '🇺🇬', isoCode: 'UGA', fifaCode: 'UGA', region: 'Africa', population: 45000000, isSovereign: true },
  { id: 'HKG', alpha2: 'HK', name: 'Hong Kong', officialName: 'Hong Kong Special Administrative Region', flagUrl: 'https://flagcdn.com/w160/hk.png', emoji: '🇭🇰', isoCode: 'HKG', fifaCode: 'HKG', region: 'Asia', population: 7500000, isSovereign: false },
  { id: 'KEN', alpha2: 'KE', name: 'Kenya', officialName: 'Republic of Kenya', flagUrl: 'https://flagcdn.com/w160/ke.png', emoji: '🇰🇪', isoCode: 'KEN', fifaCode: 'KEN', region: 'Africa', population: 53000000, isSovereign: true }
];
